export const START_COMPANY_REGISTRATION_FORM_SUBMISSION =
  "START_COMPANY_REGISTRATION_FORM_SUBMISSION";
export const START_OWNERSHIP_GROUP_CREATION = "START_OWNERSHIP_GROUP_CREATION";
export const SUBMIT_COMPANY_REGISTRATION_FORM =
  "SUBMIT_COMPANY_REGISTRATION_FORM";
export const OWNERSHIP_GROUP_CREATED = "OWNERSHIP_GROUP_CREATED";
export const OWNERSHIP_GROUP_CREATION_FAILED =
  "OWNERSHIP_GROUP_CREATION_FAILED";
export const COMPANY_REGISTRATION_FORM_SUBMISSION_SUCCESSFUL =
  "COMPANY_REGISTRATION_FORM_SUBMISSION_SUCCESSFUL";
export const COMPANY_REGISTRATION_FORM_SUBMISSION_FAILED =
  "COMPANY_REGISTRATION_FORM_SUBMISSION_FAILED";

export const START_COMPANY_OWNER_REGISTRATION =
  "START_COMPANY_OWNER_REGISTRATION";
export const COMPANY_OWNER_REGISTRATION_SUCCESSFUL =
  "COMPANY_OWNER_REGISTRATION_SUCCESSFUL";
export const COMPANY_OWNER_REGISTRATION_FAILED =
  "COMPANY_OWNER_REGISTRATION_FAILED";

export const START_FETCHING_REGISTERED_COMPANIES =
  "START_FETCHING_REGISTERED_COMPANIES";
export const FETCHING_REGISTERED_COMPANIES_SUCCEEDED =
  "FETCHING_REGISTERED_COMPANIES_SUCCEEDED";
export const FETCHING_REGISTERED_COMPANIES_FAILED =
  "FETCHING_REGISTERED_COMPANIES_FAILED";
