export const START_COMPANY_REGISTRATION_FORM_SUBMISSION =
  "START_COMPANY_REGISTRATION_FORM_SUBMISSION";
export const START_OWNERSHIP_GROUP_CREATION =
    "START_OWNERSHIP_GROUP_CREATION";
export const SUBMIT_COMPANY_REGISTRATION_FORM =
  "SUBMIT_COMPANY_REGISTRATION_FORM";
export const OWNERSHIP_GROUP_CREATED = "OWNERSHIP_GROUP_CREATED";
export const OWNERSHIP_GROUP_CREATION_FAILED =
  "OWNERSHIP_GROUP_CREATION_FAILED";
export const COMPANY_REGISTRATION_FORM_SUBMISSION_SUCCESSFUL =
  "COMPANY_REGISTRATION_FORM_SUBMISSION_SUCCESSFUL";
export const COMPANY_REGISTRATION_FORM_SUBMISSION_FAILED =
  "COMPANY_REGISTRATION_FORM_SUBMISSION_FAILED";
