export const STORE_USER = "STORE_USER";
export const BEGIN_USER_AUTHENTIFICATION = "BEGIN_USER_AUTHENTIFICATION";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const AN_ERROR_OCCURED_DURING_LOGIN = "AN_ERROR_OCCURED_DURING_LOGIN";
export const RESET_WRONG_CREDENTIALS = "RESET_WRONG_CREDENTIALS";

export const BEGIN_COMPANY_OWNER_AUTHENTICATION =
  "BEGIN_COMPANY_OWNER_AUTHENTICATION";
export const COMPANY_OWNER_AUTHENTICATION_SUCCESSFUL =
  "COMPANY_OWNER_AUTHENTICATION_SUCCESSFUL";
export const COMPANY_OWNER_AUTHENTICATION_FAILED =
  "COMPANY_OWNER_AUTHENTICATION_FAILED";

export const WRONG_LOGIN_CREDENTIALS = "WRONG_LOGIN_CREDENTIALS";
export const TERMINATE_CURRENT_SESSION = "TERMINATE_CURRENT_SESSION";

export const START_CHECKING_IF_SYSTEM_ALREADY_CONFIGURED =
  "START_CHECKING_IF_SYSTEM_ALREADY_CONFIGURED";
export const SYSTEM_ALREADY_CONFIGURED = "SYSTEM_ALREADY_CONFIGURED";
export const SYSTEM_NOT_CONFIGURED = "SYSTEM_NOT_CONFIGURED";
export const ERROR_OCCURED_DURING_SYSTEM_CONFIG_CHECK =
  "ERROR_OCCURED_DURING_SYSTEM_CONFIG_CHECK";

export const START_INITIAL_SYSTEM_CONFIGURATION =
  "START_INITIAL_SYSTEM_CONFIGURATION";
export const INITIAL_SYSTEM_CONFIGURATION_SUCCESSFUL =
  "INITIAL_SYSTEM_CONFIGURATION_SUCCESSFUL";
export const INITIAL_SYSTEM_CONFIGURATION_FAILED =
  "INITIAL_SYSTEM_CONFIGURATION_FAILED";
export const ERROR_OCCURED_DURING_SYSTEM_CONFIGURATION =
  "ERROR_OCCURED_DURING_SYSTEM_CONFIGURATION";

export const START_INITIAL_EMPLOYMENT_CATEGORIES_CONFIGURATION =
  "START_INITIAL_EMPLOYMENT_CATEGORIES_CONFIGURATION";
export const INITIAL_EMPLOYMENT_CATEGORIES_CONFIGURATION_SUCCESSFUL =
  "INITIAL_EMPLOYMENT_CATEGORIES_CONFIGURATION_SUCCESSFUL";
export const INITIAL_EMPLOYMENT_CATEGORIES_CONFIGURATION_FAILED =
  "INITIAL_EMPLOYMENT_CATEGORIES_CONFIGURATION_FAILED";
export const ERROR_OCCURED_DURING_EMPLOYMENT_CATEGORIES_CONFIGURATION =
  "ERROR_OCCURED_DURING_EMPLOYMENT_CATEGORIES_CONFIGURATION";

export const START_INITIAL_SYSTEM_OWNERSHIP_GROUP_CONFIGURATION =
  "START_INITIAL_SYSTEM_OWNERSHIP_GROUP_CONFIGURATION";
export const INITIAL_SYSTEM_OWNERSHIP_GROUP_CONFIGURATION_SUCCESSFUL =
  "INITIAL_SYSTEM_OWNERSHIP_GROUP_CONFIGURATION_SUCCESSFUL";
export const INITIAL_SYSTEM_OWNERSHIP_GROUP_CONFIGURATION_FAILED =
  "INITIAL_SYSTEM_OWNERSHIP_GROUP_CONFIGURATION_FAILED";
export const ERROR_OCCURED_DURING_SYSTEM_OWNERSHIP_GROUP_CONFIGURATION =
  "ERROR_OCCURED_DURING_SYSTEM_OWNERSHIP_GROUP_CONFIGURATION";

export const START_INITIAL_SYSTEM_COMPANY_CONFIGURATION =
  "START_INITIAL_SYSTEM_COMPANY_CONFIGURATION";
export const INITIAL_SYSTEM_COMPANY_CONFIGURATION_SUCCESSFUL =
  "INITIAL_SYSTEM_COMPANY_CONFIGURATION_SUCCESSFUL";
export const INITIAL_SYSTEM_COMPANY_CONFIGURATION_FAILED =
  "INITIAL_SYSTEM_COMPANY_CONFIGURATION_FAILED";
export const ERROR_OCCURED_DURING_SYSTEM_COMPANY_CONFIGURATION =
  "ERROR_OCCURED_DURING_SYSTEM_COMPANY_CONFIGURATION";

export const START_INITIAL_GENDER_CONFIGURATION =
  "START_INITIAL_GENDER_CONFIGURATION";
export const MALE_GENDER_CONFIGURATION_SUCCESSFUL =
  "MALE_GENDER_CONFIGURATION_SUCCESSFUL";
export const FEMALE_GENDER_CONFIGURATION_SUCCESSFUL =
  "FEMALE_GENDER_CONFIGURATION_SUCCESSFUL";
export const INITIAL_GENDER_CONFIGURATION_FAILED =
  "INITIAL_GENDER_CONFIGURATION_FAILED";
export const ERROR_OCCURED_DURING_GENDER_CONFIGURATION =
  "ERROR_OCCURED_DURING_GENDER_CONFIGURATION";

export const START_FETCHING_A_SYSTEM_USER_COMPANY_DETAILS =
  "START_FETCHING_A_SYSTEM_USER_COMPANY_DETAILS";
export const FETCHING_SYSTEM_USER_COMPANY_DETAILS_SUCCEEDED =
  "FETCHING_SYSTEM_USER_COMPANY_DETAILS_SUCCEEDED";
export const FETCHING_SYSTEM_USER_COMPANY_DETAILS_FAILED =
  "FETCHING_SYSTEM_USER_COMPANY_DETAILS_FAILED";
export const FETCHING_SYSTEM_USER_COMPANY_DETAILS_EMPTY_RESULT_SET =
  "FETCHING_SYSTEM_USER_COMPANY_DETAILS_EMPTY_RESULT_SET";

export const BEGIN_CREATING_A_SESSION_LOG = "BEGIN_CREATING_A_SESSION_LOG";
export const SESSION_LOG_CREATED_SUCCESSFULLY =
  "SESSION_LOG_CREATED_SUCCESSFULLY";
export const SESSION_LOG_CREATION_FAILED = "SESSION_LOG_CREATION_FAILED";
export const ERROR_WHILE_CREATING_SESSION_LOG =
  "ERROR_WHILE_CREATING_SESSION_LOG";

// export const BEGIN_CLOSING_A_SESSION_LOG = "BEGIN_CLOSING_A_SESSION_LOG";
// export const SESSION_LOG_CLOSED_SUCCESSFULLY =
//     "SESSION_LOG_CLOSED_SUCCESSFULLY";
// export const SESSION_LOG_CLOSING_FAILED = "SESSION_LOG_CLOSING_FAILED";
// export const ERROR_WHILE_CLOSING_SESSION_LOG =
//     "ERROR_WHILE_CLOSING_SESSION_LOG";
