export const STORE_USER = "STORE_USER";
export const BEGIN_USER_AUTHENTIFICATION = "BEGIN_USER_AUTHENTIFICATION";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const AN_ERROR_OCCURED_DURING_LOGIN = "AN_ERROR_OCCURED_DURING_LOGIN";

export const BEGIN_COMPANY_OWNER_AUTHENTICATION =
  "BEGIN_COMPANY_OWNER_AUTHENTICATION";
export const COMPANY_OWNER_AUTHENTICATION_SUCCESSFUL =
  "COMPANY_OWNER_AUTHENTICATION_SUCCESSFUL";
export const COMPANY_OWNER_AUTHENTICATION_FAILED =
  "COMPANY_OWNER_AUTHENTICATION_FAILED";

export const WRONG_LOGIN_CREDENTIALS = "WRONG_LOGIN_CREDENTIALS";
export const TERMINATE_CURRENT_SESSION = "TERMINATE_CURRENT_SESSION";
