export const STORE_USER = "STORE_USER";
export const BEGIN_USER_AUTHENTIFICATION = "BEGIN_USER_AUTHENTIFICATION";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const ATTEMPTED_USER_LOGIN_FAILED = "ATTEMPTED_USER_LOGIN_FAILED";
export const TERMINATE_CURRENT_SESSION = "TERMINATE_CURRENT_SESSION";
