export const START_CREATING_A_COMPANY_BRANCH =
  "START_CREATING_A_COMPANY_BRANCH";
export const COMPANY_BRANCH_CREATED_SUCCESSFULLY =
    "COMPANY_BRANCH_CREATED_SUCCESSFULLY";
export const COMPANY_BRANCH_CREATION_FAILED =
    "COMPANY_BRANCH_CREATION_FAILED";
