export const BEGIN_CLIENT_DETAILS_SUBMISSION =
  "BEGIN_CLIENT_DETAILS_SUBMISSION";
export const CLIENT_DETAILS_SUBMITTED_SUCCESSFULLY =
  "CLIENT_DETAILS_SUBMITTED_SUCCESSFULLY";
export const CLIENT_DETAILS_SUBMISSION_FAILED =
  "CLIENT_DETAILS_SUBMISSION_FAILED";
export const ERROR_WHILE_SUBMITING_CLIENT_DETAILS =
  "ERROR_WHILE_SUBMITING_CLIENT_DETAILS";

export const START_UPDATING_CLIENT_EMPLOYMENT_DETAILS =
  "START_UPDATING_CLIENT_EMPLOYMENT_DETAILS";
export const CLIENT_EMPLOYMENT_DETAILS_UPDATE_SUCCESSFUL =
  "CLIENT_EMPLOYMENT_DETAILS_UPDATE_SUCCESSFUL";
export const CLIENT_EMPLOYMENT_DETAILS_UPDATE_FAILED =
  "CLIENT_EMPLOYMENT_DETAILS_UPDATE_FAILED";
export const ERROR_WHEN_UPDATING_CLIENT_EMPLOYMENT_DETAILS =
  "ERROR_WHEN_UPDATING_CLIENT_EMPLOYMENT_DETAILS";
