export const BEGIN_CLIENT_DETAILS_SUBMISSION =
  "BEGIN_CLIENT_DETAILS_SUBMISSION";
export const CLIENT_DETAILS_SUBMITTED_SUCCESSFULLY =
  "CLIENT_DETAILS_SUBMITTED_SUCCESSFULLY";
export const CLIENT_DETAILS_SUBMISSION_FAILED =
  "CLIENT_DETAILS_SUBMISSION_FAILED";
export const ERROR_WHILE_SUBMITING_CLIENT_DETAILS =
  "ERROR_WHILE_SUBMITING_CLIENT_DETAILS";

export const START_UPDATING_CLIENT_EMPLOYMENT_DETAILS =
  "START_UPDATING_CLIENT_EMPLOYMENT_DETAILS";
export const CLIENT_EMPLOYMENT_DETAILS_UPDATE_SUCCESSFUL =
  "CLIENT_EMPLOYMENT_DETAILS_UPDATE_SUCCESSFUL";
export const CLIENT_EMPLOYMENT_DETAILS_UPDATE_FAILED =
  "CLIENT_EMPLOYMENT_DETAILS_UPDATE_FAILED";
export const ERROR_WHEN_UPDATING_CLIENT_EMPLOYMENT_DETAILS =
  "ERROR_WHEN_UPDATING_CLIENT_EMPLOYMENT_DETAILS";

export const BEGIN_ADDING_LOAN_DETAILS = "BEGIN_ADDING_LOAN_DETAILS";
export const LOAN_DETAILS_ADDED_SUCCESSFULLY =
  "LOAN_DETAILS_ADDED_SUCCESSFULLY";
export const LOAN_DETAILS_ADDITION_FAILED = "LOAN_DETAILS_ADDITION_FAILED";
export const ERROR_WHILE_ADDING_LOAN_DETAILS =
  "ERROR_WHILE_ADDING_LOAN_DETAILS";

export const START_FETCHING_A_COMPANYS_PENDING_LOANS =
  "START_FETCHING_A_COMPANYS_PENDING_LOANS";
export const FETCHING_THE_COMPANYS_PENDING_LOANS_SUCCEEDED =
  "FETCHING_THE_COMPANYS_PENDING_LOANS_SUCCEEDED";
export const FETCHING_THE_COMPANYS_PENDING_LOANS_FAILED =
  "FETCHING_THE_COMPANYS_PENDING_LOANS_FAILED";
export const FETCHING_THE_COMPANYS_PENDING_LOANS_EMPTY_RESULT_SET =
  "FETCHING_THE_COMPANYS_PENDING_LOANS_EMPTY_RESULT_SET";

export const TOGGLE_MODAL_DISPLAY = "TOGGLE_MODAL_DISPLAY";
export const RESET_CLIENT_DB_ID = "RESET_CLIENT_DB_ID";
export const RESET_CUSTOMER_ADDED_SUCCESSFULLY =
  "RESET_CUSTOMER_ADDED_SUCCESSFULLY";

export const GENERIC_SEARCH_SUCCESSFUL =
    "GENERIC_SEARCH_SUCCESSFUL";
export const GENERIC_SEARCH_EMPTY_RESULT_SET =
    "GENERIC_SEARCH_EMPTY_RESULT_SET";
