export const BEGIN_CLIENT_DETAILS_SUBMISSION =
    "BEGIN_CLIENT_DETAILS_SUBMISSION";
export const CLIENT_DETAILS_SUBMITTED_SUCCESSFULLY =
    "CLIENT_DETAILS_SUBMITTED_SUCCESSFULLY";
export const CLIENT_DETAILS_SUBMISSION_FAILED =
    "CLIENT_DETAILS_SUBMISSION_FAILED";
export const ERROR_WHILE_SUBMITING_CLIENT_DETAILS =
    "ERROR_WHILE_SUBMITING_CLIENT_DETAILS";

